import Head from "next/head";
import Navbar from "../../Components/Navbar/navabar";

import styles from "../../styles/Home.module.css";
import { Fragment } from "react";
import DisplayTodo from "../../Components/Todo/DisplayTodo";

export default function CompleteTodo() {
  return (
    <Fragment>
      <Navbar />
      <div className={styles.container}>
        <Head>
          <title>TODO</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>Completed Todo List</h1>
        </main>
      </div>

      <DisplayTodo />
    </Fragment>
  );
}
